version: "3"

services:
  php:
    container_name: php
    build:
      context: ./php
    ports:
      - 8080:80
    volumes:
      - ./src:/var/www/html

  db:
    container_name: db
    image: postgres:12
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - "./db/init:/docker-entrypoint-initdb.d"
    ports:
      - "5432:5432"